alias ls='ls -lahGp '
alias ll='ls -lahGp '
alias vm='nvim '
alias vim='nvim '
alias wget='curl -L -O '
alias git-clean-local='git branch --merged master | grep -v master | xargs -p -n 1 git branch -d'
alias git-clean-remote='git fetch origin; git remote prune origin; git branch -r --merged master | grep -v master | sed s/origin\\/// | xargs -p -n 1 git push origin --delete'
